[Version]
data_version =     "1.1"                    # 数据结构版本号
create_time  = 2025-12-31T11:45:14Z         # 创建时间 (UTC | yyyy-mm-ddThh:mm:ssZ)
update_time  = 2025-12-31T11:45:14Z         # 最近修改时间 (UTC | yyyy-mm-ddThh:mm:ssZ)

[Master]
CIDR =                  "172.20.159.0/28"   # 必选/Required
country.name =          "China"             # 可选/Optional | 如未填写则fallback_to_master字段强制为false
country.code =          "CN"                # 可选/Optional
source =                "DN42"              # 必选/Required | Can be DN42, NeoNetwork, ICVPN, ChaosVPN, CRXN, or other networks interconnected with DN42

[[GeoData]]
CIDR =                  "172.20.159.1/32"   # 必选/Required
anycast =               false               # 可选/Optional | 默认false / example flase
country.name =          "Japan"             # 必选/Required
country.code =          "JP"                # 必选/Required
region.name =           "Tokyo"             # 可选/Optional
region.code =           "13"                # 可选/Optional
city =                  "Tokyo"             # 可选/Optional
latitude =              35.6937632          # 必选/Required
longitude =             139.7036319         # 必选/Required
accuracy_radius=        50                  # 必选/Required

# 试验性 / Experimental
address.default =      ""                  # 可选/Optional
address.de =           ""                  # 可选/Optional
address.en =           ""                  # 可选/Optional
address.es =           ""                  # 可选/Optional
address.fr =           ""                  # 可选/Optional
address.ja =           ""                  # 可选/Optional
address.pt-BR =        ""                  # 可选/Optional
address.ru =           ""                  # 可选/Optional
address.zh-hans =      ""                  # 可选/Optional
address.zh-hant =      ""                  # 可选/Optional

[[GeoData]]
CIDR =                  "172.20.159.14/32"   # 必选/Required
anycast =               true                 # 可选/Optional | 默认false / example flase